### PR TITLE
Bunch of things; tests, code coverage, linting and more.

### PR DESCRIPTION
**Pull request by ChrisAlderson**
This PR probably has a bit much, so if you close or cherry pick changes I understand.

 - Deleted some seemingly unused code in `index.js`
 - Module now exports an ES6 class instead of an object. (breaking backwards compatibility)
 - Unit tests with [mocha](https://github.com/mochajs/mocha) and [chai](https://github.com/chaijs/chai)
 - Added code coverage with [nyc](https://github.com/istanbuljs/nyc)
 - Linting with [StandardJS](https://github.com/standard/standard)
 - Added npm scripts to `package.json` for linting, testing and code coverage
 - Added `.travis.yml` for CI
 - Extended `.gitignore` with [github/gitignore](https://github.com/github/gitignore/blob/master/Node.gitignore) and a bit of my own expirience
 - Added a `LICENSE.txt` file containing the MIT license
 - `package-lock.json` added generated by `npm@5`

### CODE REVIEW

**Comment by grantholle** [comment]
Wow man, thanks! Things are looking 💯

When trying to run `coveralls` I get `./coverage/lcov.info` not found. Should that be checked in as well?

**Comment by ChrisAlderson** [comment]
`coveralls` should only run in the CI as you can see [here](https://github.com/ChrisAlderson/rarbg/blob/master/.travis.yml#L23), this will publish the coverage report to [coveralls.io](https://coveralls.io/).

Also keep in mind that if you merge this PR you will need to change/remove the shields in the `README.md`.

**Comment by grantholle** [comment]
Ok got it!

Thanks again for your work on this

**Comment by ChrisAlderson** [comment]
np, had fun working on it.

**Pull request merged**
